language: scala

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - sbt "$TEST_SCRIPT"

env:
  - TEST_SCRIPT=";++2.10.4; root/checkGenerate; root/test"
  - TEST_SCRIPT=";++2.11.1; root211/checkGenerate; root211/test"

